services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bone-bridge
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
