spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${PG_HOST}:${DB_PORT:5432}/${PG_DB_NAME}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}

logging:
  level:
    org.springframework.web: INFO
    org.springframework.orm.jpa: INFO
