spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bone-bridge
    username: postgres
    password: postgres

logging:
  level:
    org.springframework.web: INFO
    org.springframework.orm.jpa: INFO

server:
  port: 8080
  servlet:
    contextPath: /api
