spring:
  application:
    name: bone-bridge.back
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog.yaml
    enabled: true
    liquibase-schema: liquibase
  output:
    ansi:
      enabled: always
  profiles:
    default: dev

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info,health
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
