spring:
  application:
    name: bone-bridge.back
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bone-bridge
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog.yaml
    enabled: true
    liquibase-schema: liquibase
  output:
    ansi:
      enabled: always
  profiles:
    default: dev

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info,health
  endpoint:
    info:
      enabled: true
    health:
      enabled: true

logging:
  level:
    org.springframework.web: INFO

server:
  port: 8080
  servlet:
    contextPath: /
