include: package:flutter_lints/flutter.yaml

# https://dart.dev/guides/language/analysis-options
linter:
  # https://dart.dev/lints.
  rules:
    avoid_print: true
    prefer_single_quotes: true
    prefer_relative_imports: true
