include: package:flutter_lints/flutter.yaml

# https://dart.dev/guides/language/analysis-options
analyzer:
  exclude:
    - lib/**/*.chopper.dart
    - lib/**/*.g.dart
linter:
  # https://dart.dev/lints.
  rules:
    avoid_print: true
    prefer_single_quotes: true
    prefer_relative_imports: true
