name: app
description: 'App project'
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  annotations:
    path: ../annotations/
  appwrite: ^13.0.0
  chopper: ^8.0.2
  collection: ^1.18.0
  crypto: ^3.0.5
  cupertino_icons: ^1.0.8
  encrypt: ^5.0.3
  flex_color_scheme: ^7.3.1
  fluentui_system_icons: ^1.1.255
  get_it: ^7.7.0
  go_router: ^14.2.7
  intl: any
  json_annotation: ^4.9.0
  package_info_plus: ^8.0.2
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  chopper_generator: ^8.0.2
  flutter_lints: ^4.0.0
  generators:
    path: ../generators/
  json_serializable: ^6.8.0
  test: any

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/license.txt
