name: app
description: 'App project'
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  annotations:
    path: ../annotations/
  cupertino_icons: ^1.0.8
  go_router: ^14.2.7
  flex_color_scheme: ^7.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^4.0.0
  generators:
    path: ../generators/
  test: any

flutter:
  uses-material-design: true
