builders:
  app_page_route_builder:
    target: ':app_page_route_builder'
    import: 'package:generators/builder.dart'
    builder_factories: ['appPageRouteBuilder']
    build_extensions: { '.dart': ['.page_route.dart'] }
    auto_apply: dependents
    build_to: source
