databaseChangeLog:
  - changeSet:
      id: C001
      author: zp1ke
      changes:
        - createTable:
            tableName: user_configs
            columns:
              - column:
                  name: id
                  type: bigint
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: code
                  type: varchar(50)
                  constraints:
                    nullable: false
              - column:
                  name: created_at
                  type: timestamp with time zone
                  constraints:
                    nullable: false
              - column:
                  name: updated_at
                  type: timestamp with time zone
                  constraints:
                    nullable: false
              - column:
                  name: user_id
                  type: varchar(50)
                  constraints:
                    nullable: false
              - column:
                  name: max_organizations
                  type: smallint
                  constraints:
                    nullable: false
              - column:
                  name: max_products
                  type: smallint
                  constraints:
                    nullable: false
        - createIndex:
            columns:
              - column:
                  name: code
              - column:
                  name: user_id
            indexName: user_configs_unq_code_user_id
            tableName: user_configs
            unique: true
        - createIndex:
            columns:
              - column:
                  name: code
            indexName: user_configs_idx_code
            tableName: user_configs
        - createIndex:
            columns:
              - column:
                  name: user_id
            indexName: user_configs_idx_user_id
            tableName: user_configs
        - createIndex:
            columns:
              - column:
                  descending: true
                  name: created_at
            indexName: user_configs_idx_created_at
            tableName: user_configs
        - createIndex:
            columns:
              - column:
                  descending: true
                  name: updated_at
            indexName: user_configs_idx_updated_at
            tableName: user_configs
