databaseChangeLog:
  - changeSet:
      id: C002
      author: zp1ke
      changes:
        - createTable:
            tableName: organizations_configs
            columns:
              - column:
                  name: id
                  type: bigint
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: code
                  type: varchar(50)
                  constraints:
                    nullable: false
              - column:
                  name: created_at
                  type: timestamp with time zone
                  constraints:
                    nullable: false
              - column:
                  name: updated_at
                  type: timestamp with time zone
                  constraints:
                    nullable: false
              - column:
                  name: organization_code
                  type: varchar(50)
                  constraints:
                    nullable: false
              - column:
                  name: max_products
                  type: smallint
                  constraints:
                    nullable: false
              - column:
                  name: max_contacts
                  type: smallint
                  constraints:
                    nullable: false
        - createIndex:
            columns:
              - column:
                  name: code
              - column:
                  name: organization_code
            indexName: organizations_configs_unq_code_organization_code
            tableName: organizations_configs
            unique: true
        - createIndex:
            columns:
              - column:
                  name: code
            indexName: organizations_configs_idx_code
            tableName: organizations_configs
        - createIndex:
            columns:
              - column:
                  name: organization_code
            indexName: organizations_configs_idx_organization_code
            tableName: organizations_configs
        - createIndex:
            columns:
              - column:
                  descending: true
                  name: created_at
            indexName: organizations_configs_idx_created_at
            tableName: organizations_configs
        - createIndex:
            columns:
              - column:
                  descending: true
                  name: updated_at
            indexName: organizations_configs_idx_updated_at
            tableName: organizations_configs
